In [3]:
import numpy as np

In [11]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr2)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [15]:
## 3x3 array of zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# 2x4 array of ones
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
# 2x2 array filled with 7
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [21]:
# 4x4 identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
 # [1, 3, 5, 7, 9] (like range)
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [37]:
 # [0. 0.25 0.5 0.75 1.] (evenly spaced)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
 #Checking Array Properties
arr = np.array([[10,20,30],[40,50,60]])
 # (2, 3) → 2 rows, 3 columns
print("Shape",arr.shape)
# 6 → total elements
print("Size",arr.size)
 # 2 → 2D array
print("Dimension",arr.ndim)
# int64 (or int32 on Windows)
print("Data type",arr.dtype)

Shape (2, 3)
Size 6
Dimension 2
Data type int32


In [97]:
# Changing Data Types
arr = np.array([1,2,3])
print(arr.dtype)
arr.dtype=np.float32
print(arr.dtype)

int32
float32


In [101]:
arr1=np.array([1,2,3], dtype=np.float32)
print(arr1.dtype)
arr_int = arr1.astype(np.int32) # Convert float to int
print(arr_int)
print(arr_int.dtype)

float32
[1 2 3]
int32


In [111]:
#Reshaping  Arrays
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
#Change shape
reshaped = arr.reshape(3,2)
print(reshaped)
print(reshaped.shape)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [115]:
#Flattening Arrays
arr = np.array([[1,2,3],[4,5,6]])
flattened =arr.flatten() # Convert 2D → 1D
print(flattened)

[1 2 3 4 5 6]
