In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [13]:
#Changing Data Types
arr_float = np.array([1.5,2.7,3.9])
print(arr_float)
print(arr_float.dtype)
arr_int = arr_float.astype(np.int32)
print(arr_int)
print(arr_int.dtype)

[1.5 2.7 3.9]
float64
[1 2 3]
int32


In [37]:
arr1_int = np.array([1,2,3,4])
print(arr1_int.dtype)
arr1_int.dtype=np.float32
print(arr1_int.dtype)
print(arr1_int)

int32
float32
[1.e-45 3.e-45 4.e-45 6.e-45]


In [39]:
arr3 = np.array([23,24,25,26])


In [41]:
arr3.dtype

dtype('int32')

In [43]:
arr3.astype("float64")

array([23., 24., 25., 26.])

In [45]:
arr3.dtype

dtype('int32')

In [51]:
#Memory Usage
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

print(arr_int64.nbytes)  # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)  # Output: 12 bytes (3 elements * 4 bytes each)

24
12


In [53]:
#String Data Type in NumPy
arr = np.array(['apple', 'banana', 'cherry'], dtype='U10')  # Unicode string array
print(arr)

['apple' 'banana' 'cherry']


In [55]:
#Complex Numbers
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [57]:
#Object Data Type
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)

[{'a': 1} list([1, 2, 3]) 'hello']
