In [15]:
import numpy as np

In [19]:
#Create a 3×3 array filled with random numbers and print its shape.
#create 3x3 matrix raandomy but it floating
#myarr = np.random.rand(3,3) 
myarr = np.random.randint(0,10,size=(3,3))
myarr

array([[1, 9, 7],
       [9, 4, 0],
       [5, 8, 8]])

In [33]:
#Convert an array of floats [1.1, 2.2, 3.3] into integers.
arr1 = np.array([1.1,2.2,3.3])
arr1.dtype
arr_int = arr1.astype(np.int32)
arr_int.dtype

dtype('int32')

In [61]:
#Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
arr2 = np.array([1,2,3,4,5,6])
even = (arr2%2==0)
print(arr2[even])

[2 4 6]


In [47]:
#Reshape a 1D array of size 9 into a 3×3 matrix.
arr3 = np.array([1,2,3,4,5,6,7,8,9])
reshaped = arr3.reshape(3,3)
print(reshaped)
print(reshaped.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [77]:
#Use boolean masking to filter numbers greater than 50 in an array.
arr4 = np.random.randint(1,100,size=10)
print(arr4)
mask = arr4>50
print(arr4[mask])

[22 51 11  3 31 11 77 30  1 88]
[51 77 88]
