In [1]:
import numpy as np

In [15]:
myarr = np.array([10,20,30,40,50])

In [23]:
#Indexing (Same as Python Lists)
print(myarr[0])
print(myarr[-1])
print(myarr[4])
print(myarr.size)

10
50
50
5


In [19]:
#Slicing (Extracting Parts of an Array)
print(myarr[1:4])# [20 30 40] (slice from index 1 to 3)
print(myarr[:3])# [10 20 30] (first 3 elements)
print(myarr[::2])# [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


In [27]:
#Slicing returns a view, not a copy! Changes affect the original array.**
flat = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])


In [31]:
b=flat[3:7]
b #b is a view 

array([4, 5, 6, 7])

In [33]:
b[0] = 4444
b

array([4444,    5,    6,    7])

In [35]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12,   13])

In [41]:
c=flat[0:3].copy() # We want to make a copy by our own
c

array([1, 2, 3])

In [43]:
c[0] = 11111
c

array([11111,     2,     3])

In [45]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12,   13])

In [53]:
#Fancy Indexing (Select Multiple Elements)
idx = [0,2,4] # Indices to select
print(myarr[idx])
print(myarr)

[10 30 50]
[10 20 30 40 50]


In [57]:
#Boolean Masking (Filter Data)
mask = myarr>25 # Condition: values greater than 25
print(myarr[mask])
#This is a powerful way to filter large datasets efficiently!

[30 40 50]
