In [3]:
import numpy as np

In [5]:
arr = np.array([3,5,2,33])

In [7]:
# Compute the mean (average) of an array.
np.mean(arr)

10.75

In [9]:
#Compute the standard deviation of an array.
np.std(arr)

12.891373084353738

In [11]:
#Compute the variance of an array.
np.var(arr)

166.1875

In [13]:
#Compute the minimum value of an array.
np.min(arr)

2

In [15]:
#Compute the maximum value of an array.
np.max(arr)

33

In [17]:
# Compute the sum of all elements in an array.
np.sum(arr)

43

In [21]:
# Compute the product of all elements in an array.
np.prod(arr)

990

In [23]:
#Compute the median of an array.
np.median(arr)

4.0

In [25]:
# Compute the percentile of an array.
np.percentile(arr,50)# For the 50th percentile (median)

4.0

In [27]:
#Return the index of the minimum value in an array.
np.argmin(arr)

2

In [29]:
# Return the index of the maximum value in an array.
np.argmax(arr)

3

In [31]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

In [33]:
#Compute the correlation coefficient matrix of two arrays.
np.corrcoef(arr1,arr2)

array([[1., 1.],
       [1., 1.]])

In [37]:
arr3 = np.array([1,2,3,4])
arr4=np.array([2,3,5,6])

In [43]:
#Find the unique elements of an array.
np.unique(arr)

array([ 2,  3,  5, 33])

In [45]:
#Compute the n-th differences of an array.
np.diff(arr)

array([ 2, -3, 31])

In [47]:
#Compute the cumulative sum of an array.
np.cumsum(arr)

array([ 3,  8, 10, 43])

In [49]:
#Create an array with evenly spaced numbers over a specified interval.
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [51]:
#Compute the natural logarithm of an array.
np.log(arr)

array([1.09861229, 1.60943791, 0.69314718, 3.49650756])

In [53]:
#Compute the exponential of an array.
np.exp(arr)

array([2.00855369e+01, 1.48413159e+02, 7.38905610e+00, 2.14643580e+14])