In [1]:
import numpy as np

In [ ]:
#Understanding Axes in NumPy
#1D array → 1 axis (axis 0)
#2D array → 2 axes (axis 0 = rows, axis 1 = columns)
#3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)

In [3]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr[0]

array([1, 2, 3])

In [7]:
arr[1]

array([4, 5, 6])

In [25]:
#Axes in a 2D Array
np.sum(arr,axis=0)# Sum along rows (down each column)

array([12, 15, 18])

In [27]:
np.sum(arr,axis=1)# Sum along columns (across each row)

array([ 6, 15, 24])

In [13]:
#Indexing in Multidimensional Arrays
# Row index 1, Column index 2 → Output: 6 [4,5,6] is row index 1 and 6 is the 2nd elemnt col wise
print(arr[1,2])

6


In [15]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [41]:
#Indexing in 3D Arrays
arr3D = np.array([
    [[1,2,3],
    [4,5,6]],
    
[[7,8,9],
[10,11,12]]
])
print(arr3D)
# Output of arr3D.shape is → (depth, rows, columns)
print(arr3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [43]:
# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6

print(arr3D[:, 0, :])   # Get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]


In [45]:
#Practical Example: Selecting Data Along Axes
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)  # Output: [1 4 7]

[1 4 7]


In [47]:
# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

[[1 2 3]
 [7 8 9]]


In [49]:
#Changing Data Along an Axis
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]


In [51]:
arr3D[:,0,:]=0
print(arr3D)

[[[ 0  0  0]
  [ 4  5  6]]

 [[ 0  0  0]
  [10 11 12]]]
