In [4]:
import numpy as np

In [5]:
import time

In [6]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
list(zip(l1,l2))

[(1, 5), (2, 6), (3, 7), (4, 8)]

In [ ]:
#Adding Two Lists vs. NumPy Arrays

In [10]:
#Usin Python List
size = 1_000_000_0
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x+y for x,y in zip(list1,list2)]
end = time.time()
print(result[0:10])
print("python list additiion time",end-start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
python list additiion time 0.5433204174041748


In [11]:
#Using Numpy array
size = 1_000_000_0
arr1 = np.array(list(range(size)))
arr2 = np.array(list(range(size)))
start = time.time()
add = arr1+arr2
end = time.time()
print(add[0:10])
print("Numpy array addition time:",end-start)

[ 0  2  4  6  8 10 12 14 16 18]
Numpy array addition time: 0.011007308959960938


In [32]:
#Creating numpy array
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [18]:
#Creating 2D numpy array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [34]:
#Checking type and shape
print("Type :",type(arr1))
print("Type :",type(arr2))
print("Shape :",arr1.shape)
print("Shape :",arr2.shape)

Type : <class 'numpy.ndarray'>
Type : <class 'numpy.ndarray'>
Shape : (5,)
Shape : (2, 3)


In [22]:
#Lets check the memory consumption
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size :" ,sys.getsizeof(list_data)*len(list_data),"bytes")
print("Numpy array size :",numpy_data.nbytes,"bytes")

Python list size : 8056000 bytes
Numpy array size : 4000 bytes


In [46]:
#No loops in numpy array
list1 = [1,2,3,4]
#Python list(loop-based)
start = time.time()
list_squares = [x ** 2 for x in list1]
end = time.time()
print(list_squares)
print("Python list time",end-start)

[1, 4, 9, 16]
Python list time 0.0


In [48]:
#Numpy(Vectorized using SIMD)
arr1 = np.array([1,2,3,4])
numpy_squares = arr1 ** 2
start = time.time()
print(numpy_squares)
end=time.time()
print("Numpy time",end-start)

[ 1  4  9 16]
Numpy time 0.0008387565612792969
